### PR TITLE
Extraction & Calstis CCD Jupyter Notebooks

### PR DESCRIPTION
**Pull request by KeyiDing**
Comments on the 1-D Extraction and Calstis CCD Jupyter Notebooks

### CODE REVIEW

**Comment by ymamay** [comment]
Extraction
Introduction: add why you might want to visualize it, to help figure out a custom extraction if there are multiple sources, extended background, etc.

Collect data set: still not sure what ‘objscy’ is?  Any info about this example data set like FUV, G140L, etc.  Could also say explicitly that you are downloading some data to use as an example.

x1d fits file structure: again add a short note about the CCD “(note that for CCD data the similar extension is _sx1)”.  The table note about pixel N is a bit confusing.  Are you referring to the widths here? Could you add a2center to the tables?

Plot the extraction region: labels left and middle, or right and left are not consistent in this section.  Thinking you could show the 1d extracted spectrum as a third (right) plot (this would be the ‘final’ flux vs wave plot), or maybe that doesn’t fit with the zoomed in ones.  Also the light blue (cyan) on blue is hard to distinguish, would suggest changing one of them.  Really like the different zoomed in plots.

STIS echelle: visualizing extracted region also applies to echelles data -> visualizing the extracted region also applies to echelle data

Think it would be nice if at the end you could say that if after visualizing the extraction would like to do their own custom extraction, they can run stistools.x1d (https://stistools.readthedocs.io/en/latest/x1d.html) with new specified parameters, like a2center, extrsize, bk1size, bk2size, bk1offst, and bk2offst.

**Comment by ymamay** [comment]
Calstis 2D CCD data reduction

Introduction: Add that is is only the first set of steps, so going from raw to flt. Could add this here “…common to imaging and spectroscopy for creating the _flt data product from _raw)”. Then you could also add something about the negative counts after this “This notebook also shows how negative count values are produced in the pipeline.”

Collect data: would add something about the example data set, like what mode, aperture, etc (CDD, G430L, 52x0.2)

Define functions: I don’t think normalized is quite the right word here for describing the range and would add the units (counts) and type to the table (tuple or list with 2 elements?).  “Range for displaying the data in the both the image and histogram in counts” and “The science data is shown as an image with the colors spanning the range we specified through the ran parameter, and the same range applies to the histogram boundaries.”

BLEVCORR: still something weird with formatting here: 062(serial)1044(parallel) pixels, with 10241024 exposed

Could add a note about how the ranges chosen are to optimize seeing the counts in the background.  The science target has higher counts than what can be seen in the histograms.  Since this applies to all the steps, this could go where you first plot the raw data.

**Comment by m-dallas** [comment]
view data:

**Section 4.1**
Possibly make the histogram bins one wider to calculate the number of pixels with the 16384 flag and noting that the flag will only apply to x1d/sx1 files. Could be helpful to have log y axes and return the counts array from plt.hist and add a column to dq_table which gives the number of pixels which each flag value using "counts, edges, h = plt.hist(dq_bits,bins=bins_)"

1d extraction:

Under **Extracted spectra of STIS echelles** specify which hdu to pass in table.read to avoid a warning message: Table.read(echelle_x1d,hdu=1)[["SPORDER","WAVELENGTH","FLUX","EXTRLOCY",'EXTRSIZE',"BK1SIZE","BK2SIZE","BK1OFFST","BK2OFFST"]]

And/or make a note that this observation is composed of 8 shorter exposures and we are plotting the first.

**Comment by dstapleton22** [comment]
Using hst environment. May have led to a lot of the units errors I encountered. Tables were created in those cases but errors still printed. 

1d extraction:
Typo in “Plot the Extraction Region” section, says Cryan instead of Cyan. 

Possible typo in “Extracted Spectra of STIS Echelle” section, says “echelles data”. 

Received errors when running- Table.read(x1d_filename)[["SPORDER","WAVELENGTH","FLUX","EXTRLOCY",'EXTRSIZE',"BK1SIZE","BK2SIZE","BK1OFFST","BK2OFFST"]]

"WARNING: UnitsWarning: 'Angstroms' did not parse as fits unit: At col 0, Unit 'Angstroms' not supported by the FITS standard. Did you mean Angstrom or angstrom? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'Counts/s' did not parse as fits unit: At col 0, Unit 'Counts' not supported by the FITS standard. Did you mean count? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see [https://docs.astropy.org/en/latest/units/](https://docs.astropy.org/en/latest/units/combining_and_defining.html)
WARNING: UnitsWarning: 'erg/s/cm**2/Angstrom' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]"

calstis_2d_ccd-
On import get this error- "/Users/dstapleton/miniconda3/envs/hst/lib/python3.9/site-packages/stsci/tools/nmpfit.py:8: UserWarning: NMPFIT is deprecated - stsci.tools v 3.5 is the last version to contain it.
  warnings.warn("NMPFIT is deprecated - stsci.tools v 3.5 is the last version to contain it.")
/Users/dstapleton/miniconda3/envs/hst/lib/python3.9/site-packages/stsci/tools/gfit.py:18: UserWarning: GFIT is deprecated - stsci.tools v 3.4.12 is the last version to contain it.Use astropy.modeling instead.
  warnings.warn("GFIT is deprecated - stsci.tools v 3.4.12 is the last version to contain it."

Under **Define Functions for Calibration and Showing Image** the plots output as small with broken formatting with default settings. (Photo attached) 
calstis_2d_ccd_plots

Under **DQICORR: Initialize Data Quality File** sentence: "and do a bitwise OR with the values in the bad pixel reference file table (BPIXTAB)" could be changed to "and does a bitwise OR"

Under **BLEVCORR: Large Scale Bias & Overscan Subtraction** formatting breaks at end of last paragraph due to use of "*". Also, in the paragraph after the calibration step "electronic bias level" is spelled "elextronic bias level"

view_data:
Under **section 2.2**- got same error as in the 2d notebook
"WARNING: UnitsWarning: 'Angstroms' did not parse as fits unit: At col 0, Unit 'Angstroms' not supported by the FITS standard. Did you mean Angstrom or angstrom? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'Counts/s' did not parse as fits unit: At col 0, Unit 'Counts' not supported by the FITS standard. Did you mean count? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'erg/s/cm**2/Angstrom' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]"

**section 3.3**- plots come out looking condensed in the x-direction (might tie into errors before) 

**section 5.2**- divide by zero error from filtered_data variable 
"/var/folders/hl/b2tr2lt14d34ms6gcsfbcn9c000534/T/ipykernel_71475/1102178096.py:2: RuntimeWarning: divide by zero encountered in log10
  filtered_data = [v for row in np.log10(x2d_data) for v in row if not (math.isinf(v) or math.isnan(v))]
/var/folders/hl/b2tr2lt14d34ms6gcsfbcn9c000534/T/ipykernel_71475/1102178096.py:2: RuntimeWarning: invalid value encountered in log10
  filtered_data = [v for row in np.log10(x2d_data) for v in row if not (math.isinf(v) or math.isnan(v))]"

section 6.1- when running Table.read(tag,2) get error
"WARNING: UnitsWarning: 'seconds' did not parse as fits unit: At col 0, Unit 'seconds' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]"

Also after **code** "events = Table.read(tag,1).to_pandas()
# get the good time interval from the GTI extension
start,stop = Table.read(tag,2)["START"],Table.read(tag,2)["STOP"]"

"WARNING: UnitsWarning: 'pixels' did not parse as fits unit: At col 0, Unit 'pixels' not supported by the FITS standard. Did you mean pixel? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]"

**Comment by sean-lockwood** [comment]
Some feedback on view_data.ipynb (diff generated with `nbdiff-web`):

https://stsci.box.com/s/2ii4u25jdzvp9quf62oitrf2fdmq6qrt

**Comment by sean-lockwood** [comment]
Uploaded the calstis notebook and diff for your review on Box:
https://stsci.box.com/s/2ii4u25jdzvp9quf62oitrf2fdmq6qrt

**Comment by sean-lockwood** [comment]
I just uploaded 1D_extraction notebook to box for review.

**Pull request closed without merging**
