### PR TITLE
Extraction & Calstis Jupyter Notebooks

### PR DESCRIPTION
**Pull request by KeyiDing**

### CODE REVIEW

**Comment by awfullerton** [comment]
This is a very helpful and clear tutorial!   Some extremely minor points to consider:

Section 1 - though probably beyond the scope of this notebook, it might be helpful to point to resources for how to locate the obs_id for a particular target.    Maybe say something like "assume obs_id is already known; tips on locating data sets are available {wherever}.

Section 2.1 - word-smithing "data **were** taken"

Section 2.2 - Maybe point to some documentation to tell folks how to determine which extension to grab from the hdu_list object.

Section 3 (and elsewhere) -  to get a version of the Angstrom symbol that's not italicized, use chr(197).   For example:
`xtitle = r'Wavelength [' + chr(197) +']'`

Section 4.2  -  For consistency with previous plots, use the Angstrom symbol on the ytitle rather than "Angstrom"?
Also: should the title refer to NUV rather than FUV?     As mentioned at last week's meeting, the Figure doesn't really highlight the pixels with SDQ issues.   Maybe present a blow up on a tiny region and plot the spectrum (with, without) the bad pixels in different colors?  Or overplot the flagged pixels with a big colorful symbol?  

I'm still playing with Sections 5 and 6 ...

**Comment by awfullerton** [comment]
Sections 5 and 6 look great!   I noticed one typo in Section 6:
OLD: DETAXIS1: pixel coordinate along the spectral axis without the corretion term on Doppler shifts
NEW: DETAXIS1: pixel coordinate along the spectral axis without the **corretion for** Doppler shifts

Also, I think my previous comment on Section 2.2 can be ignored....the extensions for x1d files are adequately described in Section 2.1.

**Comment by dwastro** [comment]
on the whole, this combines some very useful steps for spectrum/image examination

some of the suggestions/comments below are just due to my unfamiliarity with python details; others may be beyond the scope of this particular notebook but would be generally useful (so please keep in mind for future, perhaps more specialized notebooks)

sec. 3.1 
   in step 11, the comment on plt.plot suggests that the error array is also plotted, but it is not
                    where style options are given, is there a good reference/link for knowing what the options are --
                    e.g., how does one know what "bmh" means for plot.style.use?  or the various specs for data points style?
sec 4.2
   at some point, it might be worth adding an option to modify which flags are considered "serious" -- e.g., for the ULLYSES data, it was seen that MANY pixels were flagged for high dark rate (if I recall correctly) -- but the data were actually ok -- so we ended up keeping the data that had only that flag

sec 5.2
   in step 20, how does one know what limits to specify (vmin, vmax)? -- 
      might be worth showing a histogram of the image values to help with that
      what options are available for cmap?  
      what is the functional form of "viridis" (not obvious from the name)
   often, one wants to try different scalings and color maps to bring out features at different levels -- so knowing the range in the data and the available options for cmap would be helpful

sec 6.2
   if multiple accums are constructed from a single time-tag image, it would be useful to be able to compare them, using the same plot parameters (range, scale, color map)

in general, it might be worth looking at the various options in saoimage/ds9 (which I have often used for image examination) for ideas on options for visualization and manipulation 

at some point (perhaps not in this notebook), it would be useful to be able to compare both the 1D spectrum and the 2D image from which it was extracted -- e.g., to look for cosmic-ray hits in the 2D image (that might contribute to a "feature" in the 1D spectrum), to mark the location of the extraction box in the 2D image (to see if it is well centered on the spectrum there), to see if the FUV glow might be affecting the extracted spectrum, etc.

**Comment by dwastro** [comment]
one other useful item for the time-tag section would be a time series plot of the total flux (to see if it is roughly constant over the whole interval or if there are deviations (e.g., secular drifts due to guiding issues or temporary bumps due to passing near the edge of the SAA)

**Comment by jkcarlberg** [comment]
Great notebook!  A comment on echelle section - in the introduction paragraph, you link to the IHB section on Long-slit echelle spectroscopy. However, that is a very specialized use of the echelles because you have to worry about order overlap (where the light from one spatial location and wavelength are overlapping on the detector with light from a neighboring echelle order (i.e., wavelength) and different spatial location.)  The more common use is to use short slits, and I think you want to reference Section 4.3 instead (https://hst-docs.stsci.edu/stisihb/chapter-4-spectroscopy/4-3-echelle-spectroscopy-in-the-ultraviolet), which is the high level overview

**Comment by ymamay** [comment]
View Data Notebook- some minor text change suggestions

Could the different python package names (like inntag) be done in a different font or something?

0. operate at different wavelength, their data are organized in the same structure -> operate at different wavelengths, their data are organized in similar structure

STIS/NUV-MAMA: Cs2Te Multi-Anode Microchannel Array (MAMA) detector -> STIS/NUV-MAMA: Cs2Te Multi-Anode Microchannel Array (MAMA) detector for observing mainly in the near ltraviolet (NUV)

STIS/FUV-MAMA: Solar-blind CsI Multi-Anode Microchannel Array (MAMA) detector -> STIS/FUV-MAMA: Solar-blind CsI Multi-Anode Microchannel Array (MAMA) detector for observing mainly in the far ultraviolet (FUV)

0.1 stistools for quick operations on STIS Data -> stistools for quick operations on STIS data
Also imported ‘math’

1. ‘# Search target objscy by obs_id’. What is objscy?

2.1 Before doing any operation on the data -> Before doing any operations on the data

The Aperture extracted, background subtracted, flux and wavelength calibrated spectra data is stored in fits file with suffix _x1d. While we are using _x1d fits file as an example of investigating STIS table data, the following method of reading in data and viewing spectrum or other fields can be applied to any table data, either calibrated or uncalibrated. For more information on STIS file naming conventions, see Types of STIS Files. 
-> The aperture extracted, background subtracted, flux and wavelength calibrated spectra data is stored in the fits file with suffix ‘_x1d’ (note that for the CCD it is ‘_sx1’). While we are using the _x1d fits file as an example of investigating STIS data, the following methods for reading in data and viewing a spectrum or other fields can be applied to the other STIS data, either calibrated or uncalibrated. For more information on STIS file naming conventions, see Types of STIS Files.

or directly print the x1d_header to get -> or directly print the x1d_header_0 to get

2.2 Suggest just calling it data instead of table data

‘Another popular way of reading in fits data from hdu list as "FITS_rec”:’ This is my usual method. What is fits_rec?

3.1 plt.plot(wl, flux, #the x-data, y-data, and y-axis error -> plt.plot(wl, flux, #the x-data and y-data

plt.plot(wl_region, flux_region, #the x-data, y-data, and y-axis error -> plt.plot(wl_region, flux_region, #the x-data and y-data

[out13] the error bars are hard to see.  Could you zoom in more or make them a different color?

Are the greyed out boxes for matplotlib.pyplot.plot and error supposed to be links?

4.2 Removing "Serious Data Quality" -> Removing "Serious Data Quality Flags”

[In17] remove y-axis errors cause they are not plotted here

5.1 the fits file with the x2d extension. ->the fits file with the x2d extension (note that for the CCD the similar extension is sx2).

5.2 Make a histogram on the magnitude ->Make a histogram of the magnitude

5.3 Would add a short description such as “Now are going to remove the pixels with series data quality flags as described above.  The removed pixels will appear grey like the background.  The horizontal stripes of removed data are from the bar (top) and repeller wire shadow (middle).”

6. First collect the _tag data ->First download the _tag data

[In24] Your example here is with all the fits files, not just the science ones like before

The _tag fits file has two binary table extensions: EVENTS and GTI. -> The _tag fits file has two binary table extensions: EVENTS and GTI (Good Time Interval).

Would add somewhere, maybe after you read in the GTI header what is a good time interval, or maybe what would cause it to be different for the usual exposure time

6.2 inttag method in stistools. More information: Error and Data Quality Array - Change the link name to Inntag

# define the output file directory -> # define the output file

inttag with multiple data sets -> inttag can be run to produce multiple output imsets

7. echelles -> echelle (multiple occasions)
covering different wavelength ->covering a different wavelength

We first collect an Echelles data ->We first collect data taken with an echelle

[In 34] like with the time-tag, here you are downloading all the fits files, not just the science ones

7.2 the wavelength ranges could overlap -> some of the wavelength ranges overlap

**Pull request closed without merging**
