### PR TITLE
Update README.md in preparation for archiving this repository

### PR DESCRIPTION
**Pull request by sosey**
All the Notebooks for this repo have been migrated to the new hst_notebooks repository for continued use and maintenance.

### CODE REVIEW

**Comment by sean-lockwood** [comment]
It might be a good idea to link to the HTML page too:

https://spacetelescope.github.io/hst_notebooks/notebooks/STIS/README.html

**Comment by sosey** [comment]
hmm, I'm a little wary that the page changes and then the archived readme is wrong?

**Comment by sean-lockwood** [comment]
I'd be happy with the root page:
https://spacetelescope.github.io/hst_notebooks/

**Comment by sean-lockwood** [comment]
@emrickman, @Jackie-Brown  -

Links on this page should probably be updated in coordination with archiving this repository:  
https://www.stsci.edu/hst/instrumentation/stis/data-analysis-and-software-tools

**Comment by sosey** [comment]
> I'd be happy with the root page: https://spacetelescope.github.io/hst_notebooks/

ok, if they change the name of the repo, then other things are afoot.

**Review by sean-lockwood — APPROVED** [review]

**Comment by emrickman** [comment]
Edits made (pending publication approval via Jahia) to the links on https://www.stsci.edu/hst/instrumentation/stis/data-analysis-and-software-tools to the updated repo link and corresponding notebooks: https://www.stsci.edu/hst/instrumentation/stis/data-analysis-and-software-tools .

**Pull request merged**
